const theme = {
  background: "var(--cf-bg)",
  surface: "var(--cf-surface)",
  surfaceHover: "var(--cf-surface-hover)",
  border: "var(--cf-border)",
  borderBright: "var(--cf-border-bright)",
  text: "var(--cf-text)",
  textMuted: "var(--cf-text-muted)",
  accent: "var(--cf-accent)",
  accentBright: "var(--cf-accent-bright)",
  accentDeep: "var(--cf-accent-deep)",
  cyan: "var(--cf-secondary)",
  danger: "var(--cf-danger)",
  success: "var(--cf-success)",
  warning: "var(--cf-warning)",
  glow: "var(--cf-glow)",
  glowSoft: "var(--cf-glow-soft)",
  cyanGlow: "var(--cf-secondary-glow)",
  dangerGlow: "var(--cf-danger-glow)",
  successGlow: "var(--cf-success-glow)",
  warningGlow: "var(--cf-warning-glow)",
};
export default theme;
